- charts/trento-server/charts/trento-web/templates/_helpers.tpl
- charts/trento-server/charts/trento-web/templates/deployment.yaml
- charts/trento-server/charts/trento-web/templates/secret.yaml
- charts/trento-server/charts/trento-web/values.yaml
- scripts/install-server.sh
Adds admin user to the init container and generate password if not provided.
Added the password prompt to the install-server script,
bonus: refactored the mandatory parameters prompt to ask again if the user input was invalid.
_Please ignore the failing CI which is due the version bump, we can safely squash and merge and avoid bumping the version till we do not release in IBS for the GA._
> Add admin user initialization

- .github/workflows/ci-cd.yaml
- packaging/suse/trento-server/Makefile
- packaging/suse/trento-server/_helmignore
- packaging/suse/trento-server/_service
- packaging/suse/trento-server/values-overwrite.yaml
Include the `suse` delivery files. They are needed to ship in OBS.
Besides this, I have added a new extra step to publish the new version on OBS in every merged PR.
It would be published here: https://build.opensuse.org/package/show/devel:sap:trento:factory/trento-server-helm
> Suse delivery

- .github/workflows/ci-cd.yaml
You changes:
- Fix version usage generation for the `trento-server-installer`, same as in web, runner and agent (git CVE-2022-24765 issue)
- Add changes file update stage, to update the changes file from the github release text. Less manual work!
> Improve CI to update change file on release and fix version string generation

- .github/workflows/ci-cd.yaml
Damn, for some reason GH doesn't notify fast enough if the CI had a syntax error...
> Fix syntax error in gihtub ci file introduced in last PR

- charts/trento-server/Chart.lock
- charts/trento-server/Chart.yaml
Upgrading the postgresql chart to 11.x.x breaks the upgrade process.
Getting back to `10.x.x` version stream to try to fix it.
```Error: UPGRADE FAILED: execution error at (trento-server/charts/postgresql/templates/secrets.yaml:17:24):```
> Downgrade postgresql chart 10

- packaging/suse/trento-server-installer/trento-server-installer.spec
This PR simply changes the relationship with the old `trento-premium-server-installer` so that it's now marked as Obsolete. This should reduce the possibility of users installing the older package without noticing that it has been obsoleted.
> Change trento-premium-server-installer to be obsolete in the spec

- .github/workflows/ci-cd.yaml
- packaging/suse/trento-server-installer/trento-server-installer.spec
- packaging/suse/trento-supportconfig-plugin/_service
- packaging/suse/trento-supportconfig-plugin/trento
- packaging/suse/trento-supportconfig-plugin/trento-supportconfig-plugin.spec
- scripts/trento-support.sh
Copy-paste from the old PR in `trento-project/web`:
This PR adds a support script that customers or our L3 team can call to collect data about the installation.
The base idea is to collect everything that might help us determine what could be going wrong on the trento-server installation.
Some random thoughts:
- Do we need something on the agent side too for agent related issues? Not sure if it would make sense to have something that needs to be executed on each agent or if instead we can rely on trento-server to collect such information from here
- It would be nice if we can integrate this with supportconfig used in SLES. This script should still remain here (for non-SLES users), but could write a very simple wrapper plugin for supportconfig that call this script to collect all that it …
> Add basic script for support requests

- charts/trento-server/Chart.lock
- charts/trento-server/Chart.yaml
This should update the grafana helm chart that we use, fixing also the broken pipelines due to 1.25.x removing PodSecurityPolicy see  [this](https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp/)
> Update grafana chart dependency to 6.36.1

- charts/trento-server/Chart.lock
- charts/trento-server/Chart.yaml
- charts/trento-server/values.yaml
Basic `rabbitmq` addition from bitnami using the default values (except the username and password): 
https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq/
It is disabled by default to not break current production state.
> Add basic rabbitmq chart

- packaging/suse/trento-supportconfig-plugin/trento-supportconfig-plugin.spec
Just some cleanups removing debugging lines & unnecessary parts left in the trento supportconfig specfile.
> Cleanup debugging leftovers supportconfig specfile

- .github/workflows/dependabot_auto_merge.yaml
workflow names didn't match, so the dependabot auto merge would never happen
> fix workflow name

- charts/trento-server/Chart.yaml
According to @mrueckert, we are using non-compliant characters in the build metadata. See: https://github.com/distribution/distribution/blob/main/reference/regexp.go#L66
This should fix this issue.
> Switch + sign for - in build metadata

- charts/trento-server/Chart.lock
- charts/trento-server/Chart.yaml
Bumps the chart version (not the container) since the version was too old and removed from the repository
> Bump postgresql chart version to 12.1.6

- charts/trento-server/Chart.yaml
- charts/trento-server/templates/provision-database-permissions-job.yaml
Fix for the invalid permissions issue in the postgresql pod:
```
2023-02-02 15:29:23.771 UTC [8]FATAL: data directory "/var/lib/postgresql/data/trento" has invalid permissions
2023-02-02 15:29:23.771 UTC [8]DETAIL: Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
```
This job changes the folder permissions, so the next time the postgresql pod is started, it doesn't have this error.
Basically, it launches a container mounting the volume where the pg data is stored to change the folder permissions.
I have tested it with the community postgresql image, and with the trento-db image.
PD: In fact, if we use the official docker image or the bitnami postgresql docker image, both of them continue working, so at some point, we are ready to remove that in-house dependency and use 3rd party …
> Provision postgresql data folder permissions

- charts/trento-server/Chart.yaml
- charts/trento-server/charts/trento-wanda/Chart.yaml
- charts/trento-server/charts/trento-wanda/values.yaml
Temporary solution for the ingress and load balancer ambiguity.
Without this, the `/api/v1/...` are always redirected to the web container.
We will implement alongside this a more robust solution, using better namespaces for the services, so there is not any potential issue on this
> Add a temporary fix to wanda ingress path value to use versioning

- charts/trento-server/Chart.yaml
- charts/trento-server/charts/trento-wanda/Chart.yaml
- charts/trento-server/charts/trento-wanda/templates/_helpers.tpl
- charts/trento-server/charts/trento-wanda/templates/deployment.yaml
- charts/trento-server/charts/trento-wanda/templates/secret.yaml
- charts/trento-server/charts/trento-web/Chart.yaml
- charts/trento-server/charts/trento-web/templates/_helpers.tpl
- charts/trento-server/charts/trento-web/templates/deployment.yaml
- charts/trento-server/charts/trento-web/templates/grafana-secret.yaml
- charts/trento-server/values.yaml
Fix shared jwt access token values usage.
There where some leftovers and some names wrong. This causes that the access token was being get empty, as the used secret name was not there.
> Fix shared access token key usage

- charts/trento-server/Chart.yaml
- charts/trento-server/charts/trento-wanda/Chart.yaml
- charts/trento-server/charts/trento-wanda/templates/_helpers.tpl
- charts/trento-server/charts/trento-wanda/templates/configmap.yaml
- charts/trento-server/charts/trento-wanda/values.yaml
As the web and wanda are running using the same domain, cors usage is not needed.
Depends on: https://github.com/trento-project/wanda/pull/206
> Disable cors usage for wanda

- charts/trento-server/Chart.yaml
- charts/trento-server/charts/trento-web/Chart.yaml
- charts/trento-server/charts/trento-web/templates/prune-events-cronjob.yaml
- charts/trento-server/charts/trento-web/values.yaml
Make the days flag for the pruning task variable, leaving the 10 days as default.
In fact, this change fixes a bug we had in the cronjob (which most probably was not being executed properly). An secrets env file was not being provided
The usage would be something like:
```
helm install trento-server . --set trento-web.pruneEventsOlderThan=0 --set trento-web.pruneEventsCronjobSchedule="* * * * *" --set trento-web.adminUser.password=adminpassword
```
@abravosuse We should add the usage of these 2 variable somewhere in the docs. The `pruneEventsOlderThan` and `pruneEventsCronjobSchedule`. I could help you elaborating the text of course
For example, putting `0` means all the events will be executed (by default every hour). This has the big disadvantage that we cannot debug what happened (or …
> Make pruning crobjob days variable

- scripts/trento-support.sh
This PR:
- adds `--namespace` option to the `trento-support.sh` script to specify the namespace to be passed down to `kubectl` as argument.
- it renames the previous `--name` option to specify the installation name to `--release-name` in order to avoid confusion.
Note: this only covers the changes to the script and does _not_ include changes to the supportconfig plugin as we can't really pass down parameters to it. For cases where the customer has changed the namespace, there are two possibilities:
- Ask the customer to run the `trento-support.sh` script directly with the appropriate `--namespace`.
- Allow to configure some setting in `/etc/trento` or `$HOME/.trento` where the trento default namespace is set.
> Add namespace option

- .github/workflows/ci-cd.yaml
- packaging/suse/trento-server-installer/_service
- packaging/suse/trento-supportconfig-plugin/_service
This PR changes the _service files for the scripts and takes care of updating the OBS packages in a rolling release form on each commit to main.
> Enable rolling releases for script packages in OBS

- charts/trento-server/Chart.yaml
- charts/trento-server/charts/trento-web/Chart.yaml
- charts/trento-server/charts/trento-web/templates/configmap.yaml
- charts/trento-server/charts/trento-web/values.yaml
Together with disabling prometheus usage, add the option to disable the charts.
We can achieve that adding the next flags to helm:
```
--set prometheus.enabled=false --set trento-web.chartsEnabled=false
```
> Add option to disable charts

- scripts/trento-support.sh
This PR allows the trento supportconfig plugin (a wrapper around trento-support.sh) to use env vars as a source for both the k8s namespace and the chart installation release name.
Tested manually:
w/o env vars:
```
#==[ Command ]======================================#
NAME         STATUS   ROLES                  AGE   VERSION        INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION             CONTAINER-RUNTIME
linux-5l8b   Ready    control-plane,master   23d   v1.27.6+k3s1   172.22.99.150   <none>        openSUSE Leap 15.2   5.3.18-lp152.106-default   containerd://1.7.6-k3s1.27
#==[ Command ]======================================#
No resources found in default namespace.
#==[ Command ]======================================#
Error from server (NotFound): deployments.apps …
```
> Add env var support for the supportconfig plugin/wrapper

- charts/trento-server/Chart.yaml
- charts/trento-server/charts/trento-web/Chart.yaml
- charts/trento-server/charts/trento-web/templates/configmap.yaml
- docs/trento-server.md
- hack/cert-manager/README.md
- hack/cert-manager/certificate.tpl.yaml
- hack/cert-manager/override-values.tpl.yaml
- scripts/install-server.sh
Just a tiny fix. Please confirm I did not forget anything 😄
> Rename `TRENTO_DOMAIN` to `TRENTO_WEB_ORIGIN`

- packaging/suse/trento-server/Makefile
fixes the CI which started failing since
https://github.com/trento-project/continuous-delivery/commit/0b0bd766fdf17e2d4dbdb3516523b8a9537a54cc
due to `yq` version mismatch
> make version check less brittle and more relaxed

- charts/trento-server/Chart.yaml
- charts/trento-server/values.yaml
We need a fixed version in the values for the checks image otherwise we won't be able to bump it and having `rolling` won't trigger any redownload.
> Fix checks image tag

- charts/trento-server/Chart.yaml
- charts/trento-server/charts/trento-wanda/Chart.yaml
- charts/trento-server/charts/trento-wanda/templates/_helpers.tpl
- charts/trento-server/charts/trento-wanda/values.yaml
- charts/trento-server/charts/trento-web/Chart.yaml
- charts/trento-server/charts/trento-web/templates/_helpers.tpl
- charts/trento-server/charts/trento-web/values.yaml
Make web and wanda secret key base configurable from the outside, so the value is not auto-generated.
This can be helpful in certain scenarios where auto-generated value can have issues (for example, you constantly install/uninstall the chart without deleting the postgresql pvc).
To use it simply add `--set trento-web.secretKeyBase=secret --set trento-wanda.secretKeyBase`.
Keep in mind, that everytime this value is given it must have the same value!
If you are doing a `helm update` in the other hand, you can omit the value in the 2nd time, as the key is stored as a secret in the 1st installation, and it can be fetched from there in the 2nd time.
@abravosuse I'm putting you here, as this have some impacts. First of, it opens some scenario where the user can things even worst (they use …
> Make secret key base configurable

- scripts/install-server.sh
* remove unused function `load_conf`
* allow for injecting the tty actual reference. This is needed for systems in which the current shell is not on `/dev/tty`
```
TTY=$(readlink /proc/$$/fd/2) ./scripts/install-server.sh
```
> Small fixes on the install script

- charts/trento-server/Chart.yaml
- charts/trento-server/charts/trento-web/Chart.yaml
- charts/trento-server/charts/trento-web/templates/configmap.yaml
- charts/trento-server/charts/trento-web/templates/secret.yaml
- charts/trento-server/charts/trento-web/values.yaml
Updated trento-web chart with new default alerting settings. The new values are all `null` which have the semantics of "not explicitly set", meaning that no OS environment variables for alerting would be set in the ConfigMap. 
This allows `trento-web` to be configured for alerting via WebUI by default. Only the default values and their implication for creating ConfigMap values are changed -- old installations that already modify values with `--set` would operate as expected. 
Implementation notice: Although the implementation seems a bit repetitive, I find it the most clear and concise. Extracting the common functionality into its own "function" (or rather "named template") leads to error-prone new-line/whitespace tracking that is not idiomatic nor easy to use. IMO, using `include` with …
> Updated defaults for alerting settings

- .gitignore
- README.md
- charts/trento-server/Chart.yaml
- charts/trento-server/charts/trento-wanda/templates/configmap.yaml
- charts/trento-server/charts/trento-wanda/templates/deployment.yaml
- charts/trento-server/charts/trento-web/templates/configmap.yaml
- charts/trento-server/charts/trento-web/templates/deployment.yaml
- charts/trento-server/templates/rabbitmq-configmap.yaml
- charts/trento-server/values.yaml
- hack/rabbitmq-tls/README.md
- hack/rabbitmq-tls/generator
- hack/rabbitmq-tls/generator.Dockerfile
- scripts/create-certificates-secrets.sh
Fixes https://github.com/trento-project/helm-charts/pull/132
Superseeds https://github.com/trento-project/helm-charts/pull/133
This is a rewrite of #132 that had to be reverted due to some problems.
* TLS is disabled by default
* Certificates are uploaded into secrets. See `README` for details
* A generator script for development purposes is provided in `./hack/rabbitmq-tls`
> Setup rabbitmq tls

- charts/trento-server/Chart.yaml
- charts/trento-server/values.yaml
Make sure that the referenced rabbitmq configmap name matches the deployment name.
Addresses https://github.com/trento-project/web/pull/3624
> Make rabbitmq configmap name dynamic
