trento-project/helm-charts

charts/trento-server/charts/trento-web/templates/deployment.yaml, charts/trento-server/charts/trento-web/values.yaml, charts/trento-server/values.yaml
=> New trento dashboard

scripts/install-server.sh
* allow -w option for getopts
* don't prompt to validate password when given via parameter
=> fix setting of admin password in install-server.sh

.github/workflows/ci-cd.yaml, hack/get_version_from_git.sh, packaging/suse/config/installer.conf, packaging/suse/trento-server-installer/_service, packaging/suse/trento-server-installer/trento-server-installer.spec
Add the trento-server-installer package as a new standalone rpm package.
https://build.opensuse.org/package/show/devel:sap:trento:factory/trento-server-installer
=> Trento server installer

charts/trento-server/Chart.yaml, charts/trento-server/charts/trento-web/Chart.yaml, charts/trento-server/charts/trento-web/templates/configmap.yaml
This PR adds the Prometheus URL configuration value needed by the web container.
=> Add prometheus url env variable

charts/trento-server/Chart.lock, charts/trento-server/Chart.yaml, charts/trento-server/charts/trento-web/Chart.yaml, charts/trento-server/charts/trento-web/templates/configmap.yaml, charts/trento-server/charts/trento-web/values.yaml, scripts/install-server.sh
As above. Relates to https://github.com/trento-project/web/pull/695
=> Allow setting a custom sender for alerting notification emails

hack/gh_release_to_obs_changeset.py
Add `gh_release_to_obs_changeset.py` file to enable the CI proper execution
Fixes: https://github.com/trento-project/helm-charts/runs/7336521257?check_suite_focus=true
=> Add gh_release file to fix the CI process

scripts/trento-support.sh
Fix enabling of the compressed mode
Communicate error during collect_all
Allow compression after collect_all
Add check for jq presence
=> Fixes in trento-support about compressed output

.github/workflows/ci-cd.yaml, packaging/suse/trento-server/Makefile, packaging/suse/trento-server/_service
fix stuff according to changes in trento-project/continuous-delivery
=> update obs related CI jobs

charts/trento-server/Chart.lock, charts/trento-server/Chart.yaml, charts/trento-server/charts/trento-web/Chart.yaml, charts/trento-server/charts/trento-web/templates/_helpers.tpl, charts/trento-server/charts/trento-web/templates/secret.yaml
=> Add the env variables for new authentication system of trento-web project

packaging/suse/config/installer.conf, packaging/suse/trento-server/values-overwrite.yaml, scripts/install-server.sh
Update installation script and package installation related files to use wanda instead of the legacy runner.
=> Update installation script for wanda

scripts/trento-support.sh
runner -> wanda
Tested locally
=> Update support script with wanda

scripts/trento-support.sh
Add new `--name` flag to the supportconfig script to give the option to change the installation name.
The current hardcoded `trento-server` wouldn't work if other value is used during the installation with helm.
`trento-server` continues being the default value if the flag is not used
=> Add new name flag to supportconfig script

LICENSE, README.md, packaging/suse/trento-server-installer/trento-server-installer.spec, packaging/suse/trento-supportconfig-plugin/trento-supportconfig-plugin.spec
Update the Copyright year to 2023
=> Update copyright year to 2023

charts/trento-server/Chart.yaml, charts/trento-server/charts/trento-wanda/Chart.yaml, charts/trento-server/charts/trento-wanda/values.yaml
=> Add wanda v2 apis in ingress

README.md, packaging/suse/trento-server-installer/trento-server-installer.spec, packaging/suse/trento-supportconfig-plugin/trento-supportconfig-plugin.spec
Like the title says, this pr updates the license to 2024.
=> Update license to the year 2024

charts/trento-server/Chart.yaml, charts/trento-server/charts/trento-wanda/Chart.yaml, charts/trento-server/charts/trento-wanda/values.yaml
Add v3 path to the ingress configuration to redirect queries to wanda
=> Add v3 checks path to the ingress configuration

charts/trento-server/Chart.yaml, charts/trento-server/charts/trento-web/Chart.yaml, charts/trento-server/charts/trento-web/templates/configmap.yaml, docs/trento-server.md, scripts/install-server.sh
Use the env var provided in https://github.com/trento-project/web/pull/2671
Setting this to draft until:
- main freeze is over
- that PR has been merged
=> Add TRENTO_DOMAIN env var

charts/trento-server/Chart.yaml, charts/trento-server/charts/trento-web/Chart.yaml, charts/trento-server/charts/trento-web/values.yaml
Change `saml.spDir`. It is not really needed here, as we don't have the configuration file, but for consistency sake
=> Change saml.spDir default location

charts/trento-server/Chart.yaml, charts/trento-server/charts/trento-wanda/values.yaml
Add new `/api/v1/operations` endpoint ingress rule configuration.
=> Add operations endpoint ingress rule

.github/workflows/ci-cd.yaml
Upgrade github actions runner ubuntu version
https://github.com/actions/runner-images/issues/11101
=> Upgrade github actions runner ubuntu version

charts/trento-server/Chart.yaml, charts/trento-server/charts/trento-wanda/Chart.yaml
=> Bump wanda charts

hack/cert-manager/override-values.tpl.yaml
Add operation api paths to cert manager override template.
=> Add operation api paths to cert manager guideline
